### ISSUE TITLE
question about adding react touch events to the pad button 

### ISSUE THREAD

**Issue by jamesjsewell** [magentanova/simonRedux#1]
using the onMouseDown and onMouseUp touch equivalent (onTouchStart, onTouchEnd) to trigger the same actions as the mouse events ends the game. Is there a purpose for touch events other than triggering the same actions that the mouse events already do?

**Comment by jamesjsewell** [comment]
adding touch events does rectify issues on mobile but the emulated mouse event still gets triggered after each press which is what causes the player to lose. There is a way to disable the emulated mouse events I am sure.

**Comment by magentanova** [comment]
There is a way to solve this. (sorry i hadn't seen these)

You can detect the user agent, and thus whether the player is on desktop or mobile, when the app is loaded (put it in state if you want). So you should *either* use a touch event or a mouse event. Definitely not both. The game would end, then, because, for example, if the pattern was `red-blue-green`, then tapping red once would activate two functions (since mousedown actually is fired on mobile, just in a slightly different way — long story), and you would do `red-red`, and immediately lose.

**Comment by jamesjsewell** [comment]
Ok I will pr that soon. I actually started on a snake clone and I'm finishing it up tonight.
